const SET_LOADING = "SET_LOADING";
const SET_DATA = "SET_DATA";
const SET_ERR = "SET_ERR";
const UPDATE_CURRENT_PAGE_DATA = "SET_CURRENT_PAGE_DATA";
const FILTER_TABLE_DATA = "FILTER_TABLE_DATA";
const UPDATE_PROJECT_DETAILS = "UPDATE_PROJECT_DETAILS";

export {
  SET_LOADING,
  SET_ERR,
  SET_DATA,
  UPDATE_CURRENT_PAGE_DATA,
  FILTER_TABLE_DATA,
  UPDATE_PROJECT_DETAILS,
};
